In [1]:
import numpy as np

In [3]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
print(a[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
import numpy as np
a = np.array([1, 2, 3])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [12]:
np.empty(2)

array([1., 1.])

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [16]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [22]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [24]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],
                          [[0, 1, 2, 3], [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3], [4, 5, 6, 7]]])

In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [29]:
array_example.shape

(3, 2, 4)

In [30]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [31]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [32]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [33]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [35]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [37]:
data = np.array([1, 2, 3])
data[1]

2

In [38]:
data[0:2]

array([1, 2])

In [39]:
data[1:]

array([2, 3])

In [40]:
data[-2]

2

In [41]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [42]:
print(a[a<5])

[1 2 3 4]


In [43]:
five_up = ( a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [44]:
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [45]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [46]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [47]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [48]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [49]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [50]:
print(a[b])

[1 2 3 4]


In [51]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [52]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [58]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [59]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [60]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [61]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [63]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [64]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [66]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [68]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [70]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
b2 = a.copy()

In [72]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [74]:
data - ones

array([0, 1])

In [75]:
data * data

array([1, 4])

In [76]:
data / data

array([1., 1.])

In [77]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [78]:
b = np.array([[1, 1], [2, 2]])

In [79]:
b.sum(axis=0)

array([3, 3])

In [80]:
b.sum(axis=1)

array([2, 4])

In [81]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [83]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [84]:
a.sum()

4.8595784

In [85]:
a.min()

0.05093587

In [86]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [87]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [89]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
data[0,1]

2

In [91]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [92]:
data[0:2, 0]

array([1, 3])

In [95]:
data.max()

6

In [96]:
data.min()

1

In [97]:
data.sum()

21

In [98]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [101]:
data.max(axis=0)

array([5, 6])

In [102]:
data.max(axis=1)

array([2, 5, 6])

In [103]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [104]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [105]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [106]:
np.ones(3)

array([1., 1., 1.])

In [108]:
np.zeros(3)

array([0., 0., 0.])

In [109]:
rng = np.random.default_rng()
rng.random(3)

array([0.89112408, 0.06768311, 0.08526371])

In [110]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [111]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [112]:
rng.random((3, 2))

array([[0.54986912, 0.21272894],
       [0.85913632, 0.29029354],
       [0.86042764, 0.72881866]])

In [113]:
rng.integers(5, size=(2, 4)) 

array([[1, 1, 0, 1],
       [0, 0, 4, 0]])

In [114]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 2])

In [115]:
unique_values = np.unique(a)
print(unique_values)

[ 2 11 12 13 14 15 16 17 18 19]


In [116]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[1 3 2 2 2 1 1 1 1 1]


In [117]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [119]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [120]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [121]:
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [122]:
print(indices)

[0 1 2]


In [123]:
print(occurrence_count)

[2 1 1]


In [124]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [127]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [129]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [130]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [131]:
reversed_arr = np.flip(arr)

In [133]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [134]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [135]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [136]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [137]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [138]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


In [139]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [140]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [142]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [143]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
